### ISSUE TITLE
Slightly not responsive on Mobile

### ISSUE THREAD

**Issue by KendallDoesCoding** [rsk2/calculator#4]
The website is slightly not responsive on mobile, the ending of the box after the number gets cut off a bit.

![image](https://user-images.githubusercontent.com/84712013/185805256-f8404bcf-2ac1-475c-a977-ed952b6e83cd.png)

This is really good though, because for other projects/websites I've seen (inculding my projects) the website is not VERY responsive at all, and 10-15+ elements are messed up, here only 1 element which is easy to fix is messed up so good job @rsk2!!!

**Comment by rsk2** [comment]
You're right. Thanks for the issue @KendallDoesCoding

**Comment by rsk2** [comment]
This has been fixed
